# GPU Hot Agent - For Remote GPU Nodes
# Simple agent-only configuration

services:
  agent:
    build: .
    ports:
      - "1312:1312"
    environment:
      - GPU_HOT_MODE=agent
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1312/api/agent/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Usage on remote GPU nodes:
#   docker-compose -f docker-compose.agent.yml up -d
#
# Or single Docker command:
#   docker run -d --name gpu-hot-agent --gpus all -p 1312:1312 \
#     -e GPU_HOT_MODE=agent --restart unless-stopped \
#     ghcr.io/psalias2006/gpu-hot:latest

